### ISSUE TITLE
Ошибка в портфолио

### ISSUE THREAD

**Issue by ValentinaTihonova** [VladMak/education_personal#3]
Не отображается портфолио класса.

**Comment by VladMak** [comment]
Настроил папку, фотки туда кинуть и должно работать

**Comment by ValentinaTihonova** [comment]
![image](https://user-images.githubusercontent.com/44281649/47256094-a60af700-d4ac-11e8-8064-8d7eac3e80b8.png)
В какую из папок нужно добавить фото чтобы работало?)
